// 180305-2314M
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define SVN_REVISION_STRING "180305-2314M"
#define SVN_REVISION_NUMBER 1520291663
#define HG_REVISION_HASH_STRING "c2c7f37b1afb"
