// 150107-1945M
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define SVN_REVISION_STRING "150107-1945M"
#define SVN_REVISION_NUMBER 1420659942
#define HG_REVISION_HASH_STRING "e94f7e467181"
